version: '3.9'
services:
  f5_tts:
    build:
      context: ./tts/f5-tts
      dockerfile: Dockerfile
    ports:
    - 8001:8000
    volumes:
    - ./tts/f5-tts:/app
    - ./models/f5-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: f5-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-f5-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  tacotron2:
    build:
      context: ./tts/tacotron2
      dockerfile: Dockerfile
    ports:
    - 8002:8000
    volumes:
    - ./tts/tacotron2:/app
    - ./models/tacotron2:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: tacotron2
      PORT: '8000'
    restart: 'no'
    container_name: model-tacotron2
    stdin_open: true
    tty: true
    networks:
    - models-network
  openvoice_v2:
    build:
      context: ./tts/openvoice-v2
      dockerfile: Dockerfile
    ports:
    - 8003:8000
    volumes:
    - ./tts/openvoice-v2:/app
    - ./models/openvoice-v2:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: openvoice-v2
      PORT: '8000'
    restart: 'no'
    container_name: model-openvoice-v2
    stdin_open: true
    tty: true
    networks:
    - models-network
  fastspeech2:
    build:
      context: ./tts/fastspeech2
      dockerfile: Dockerfile
    ports:
    - 8004:8000
    volumes:
    - ./tts/fastspeech2:/app
    - ./models/fastspeech2:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: fastspeech2
      PORT: '8000'
    restart: 'no'
    container_name: model-fastspeech2
    stdin_open: true
    tty: true
    networks:
    - models-network
  styletts2:
    build:
      context: ./tts/styletts2
      dockerfile: Dockerfile
    ports:
    - 8005:8000
    volumes:
    - ./tts/styletts2:/app
    - ./models/styletts2:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: styletts2
      PORT: '8000'
    restart: 'no'
    container_name: model-styletts2
    stdin_open: true
    tty: true
    networks:
    - models-network
  glow_tts:
    build:
      context: ./tts/glow-tts
      dockerfile: Dockerfile
    ports:
    - 8006:8000
    volumes:
    - ./tts/glow-tts:/app
    - ./models/glow-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: glow-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-glow-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  tortoise_tts:
    build:
      context: ./tts/tortoise-tts
      dockerfile: Dockerfile
    ports:
    - 8007:8000
    volumes:
    - ./tts/tortoise-tts:/app
    - ./models/tortoise-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: tortoise-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-tortoise-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  chattts:
    build:
      context: ./tts/chattts
      dockerfile: Dockerfile
    ports:
    - 8008:8000
    volumes:
    - ./tts/chattts:/app
    - ./models/chattts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: chattts
      PORT: '8000'
    restart: 'no'
    container_name: model-chattts
    stdin_open: true
    tty: true
    networks:
    - models-network
  matcha_tts:
    build:
      context: ./tts/matcha-tts
      dockerfile: Dockerfile
    ports:
    - 8009:8000
    volumes:
    - ./tts/matcha-tts:/app
    - ./models/matcha-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: matcha-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-matcha-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  bark_small:
    build:
      context: ./tts/bark-small
      dockerfile: Dockerfile
    ports:
    - 8010:8000
    volumes:
    - ./tts/bark-small:/app
    - ./models/bark-small:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: bark-small
      PORT: '8000'
    restart: 'no'
    container_name: model-bark-small
    stdin_open: true
    tty: true
    networks:
    - models-network
  sherpa_onnx_offline_tts:
    build:
      context: ./tts/sherpa-onnx-offline-tts
      dockerfile: Dockerfile
    ports:
    - 8011:8000
    volumes:
    - ./tts/sherpa-onnx-offline-tts:/app
    - ./models/sherpa-onnx-offline-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: sherpa-onnx-offline-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-sherpa-onnx-offline-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  mms_tts_uzb_latin:
    build:
      context: ./tts/mms-tts-uzb-latin
      dockerfile: Dockerfile
    ports:
    - 8012:8000
    volumes:
    - ./tts/mms-tts-uzb-latin:/app
    - ./models/mms-tts-uzb-latin:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: mms-tts-uzb-latin
      PORT: '8000'
    restart: 'no'
    container_name: model-mms-tts-uzb-latin
    stdin_open: true
    tty: true
    networks:
    - models-network
  speecht5_tts:
    build:
      context: ./tts/speecht5-tts
      dockerfile: Dockerfile
    ports:
    - 8013:8000
    volumes:
    - ./tts/speecht5-tts:/app
    - ./models/speecht5-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: speecht5-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-speecht5-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  coqui_tts_vits:
    build:
      context: ./tts/coqui-tts-vits
      dockerfile: Dockerfile
    ports:
    - 8014:8000
    volumes:
    - ./tts/coqui-tts-vits:/app
    - ./models/coqui-tts-vits:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: coqui-tts-vits
      PORT: '8000'
    restart: 'no'
    container_name: model-coqui-tts-vits
    stdin_open: true
    tty: true
    networks:
    - models-network
  cosyvoice_300m:
    build:
      context: ./tts/cosyvoice-300m
      dockerfile: Dockerfile
    ports:
    - 8015:8000
    volumes:
    - ./tts/cosyvoice-300m:/app
    - ./models/cosyvoice-300m:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: cosyvoice-300m
      PORT: '8000'
    restart: 'no'
    container_name: model-cosyvoice-300m
    stdin_open: true
    tty: true
    networks:
    - models-network
  mms_tts_uzb:
    build:
      context: ./tts/mms-tts-uzb
      dockerfile: Dockerfile
    ports:
    - 8016:8000
    volumes:
    - ./tts/mms-tts-uzb:/app
    - ./models/mms-tts-uzb:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: mms-tts-uzb
      PORT: '8000'
    restart: 'no'
    container_name: model-mms-tts-uzb
    stdin_open: true
    tty: true
    networks:
    - models-network
  seamless_m4t_tts:
    build:
      context: ./tts/seamless-m4t-tts
      dockerfile: Dockerfile
    ports:
    - 8017:8000
    volumes:
    - ./tts/seamless-m4t-tts:/app
    - ./models/seamless-m4t-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: seamless-m4t-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-seamless-m4t-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  piper_tts:
    build:
      context: ./tts/piper-tts
      dockerfile: Dockerfile
    ports:
    - 8018:8000
    volumes:
    - ./tts/piper-tts:/app
    - ./models/piper-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: piper-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-piper-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  meta_voice_1b:
    build:
      context: ./tts/meta-voice-1b
      dockerfile: Dockerfile
    ports:
    - 8019:8000
    volumes:
    - ./tts/meta-voice-1b:/app
    - ./models/meta-voice-1b:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: meta-voice-1b
      PORT: '8000'
    restart: 'no'
    container_name: model-meta-voice-1b
    stdin_open: true
    tty: true
    networks:
    - models-network
  espeak_ng:
    build:
      context: ./tts/espeak-ng
      dockerfile: Dockerfile
    ports:
    - 8020:8000
    volumes:
    - ./tts/espeak-ng:/app
    - ./models/espeak-ng:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: espeak-ng
      PORT: '8000'
    restart: 'no'
    container_name: model-espeak-ng
    stdin_open: true
    tty: true
    networks:
    - models-network
  mms_tts_kaz:
    build:
      context: ./tts/mms-tts-kaz
      dockerfile: Dockerfile
    ports:
    - 8021:8000
    volumes:
    - ./tts/mms-tts-kaz:/app
    - ./models/mms-tts-kaz:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: mms-tts-kaz
      PORT: '8000'
    restart: 'no'
    container_name: model-mms-tts-kaz
    stdin_open: true
    tty: true
    networks:
    - models-network
  valle_x:
    build:
      context: ./tts/valle-x
      dockerfile: Dockerfile
    ports:
    - 8022:8000
    volumes:
    - ./tts/valle-x:/app
    - ./models/valle-x:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: valle-x
      PORT: '8000'
    restart: 'no'
    container_name: model-valle-x
    stdin_open: true
    tty: true
    networks:
    - models-network
  coqui_xtts_v2:
    build:
      context: ./tts/coqui-xtts-v2
      dockerfile: Dockerfile
    ports:
    - 8023:8000
    volumes:
    - ./tts/coqui-xtts-v2:/app
    - ./models/coqui-xtts-v2:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: coqui-xtts-v2
      PORT: '8000'
    restart: 'no'
    container_name: model-coqui-xtts-v2
    stdin_open: true
    tty: true
    networks:
    - models-network
  parler_tts_mini:
    build:
      context: ./tts/parler-tts-mini
      dockerfile: Dockerfile
    ports:
    - 8024:8000
    volumes:
    - ./tts/parler-tts-mini:/app
    - ./models/parler-tts-mini:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: parler-tts-mini
      PORT: '8000'
    restart: 'no'
    container_name: model-parler-tts-mini
    stdin_open: true
    tty: true
    networks:
    - models-network
  e2_tts:
    build:
      context: ./tts/e2-tts
      dockerfile: Dockerfile
    ports:
    - 8025:8000
    volumes:
    - ./tts/e2-tts:/app
    - ./models/e2-tts:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: e2-tts
      PORT: '8000'
    restart: 'no'
    container_name: model-e2-tts
    stdin_open: true
    tty: true
    networks:
    - models-network
  fish_speech_1_5:
    build:
      context: ./tts/fish-speech-1.5
      dockerfile: Dockerfile
    ports:
    - 8026:8000
    volumes:
    - ./tts/fish-speech-1.5:/app
    - ./models/fish-speech-1.5:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: fish-speech-1.5
      PORT: '8000'
    restart: 'no'
    container_name: model-fish-speech-1.5
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_tiny:
    build:
      context: ./stt/whisper-tiny
      dockerfile: Dockerfile
    ports:
    - 8027:8000
    volumes:
    - ./stt/whisper-tiny:/app
    - ./models/whisper-tiny:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-tiny
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-tiny
    stdin_open: true
    tty: true
    networks:
    - models-network
  sherpa_onnx_offline_stt:
    build:
      context: ./stt/sherpa-onnx-offline-stt
      dockerfile: Dockerfile
    ports:
    - 8028:8000
    volumes:
    - ./stt/sherpa-onnx-offline-stt:/app
    - ./models/sherpa-onnx-offline-stt:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: sherpa-onnx-offline-stt
      PORT: '8000'
    restart: 'no'
    container_name: model-sherpa-onnx-offline-stt
    stdin_open: true
    tty: true
    networks:
    - models-network
  funasr_paraformer:
    build:
      context: ./stt/funasr-paraformer
      dockerfile: Dockerfile
    ports:
    - 8029:8000
    volumes:
    - ./stt/funasr-paraformer:/app
    - ./models/funasr-paraformer:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: funasr-paraformer
      PORT: '8000'
    restart: 'no'
    container_name: model-funasr-paraformer
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_diarization:
    build:
      context: ./stt/whisper-diarization
      dockerfile: Dockerfile
    ports:
    - 8030:8000
    volumes:
    - ./stt/whisper-diarization:/app
    - ./models/whisper-diarization:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-diarization
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-diarization
    stdin_open: true
    tty: true
    networks:
    - models-network
  vosk_api_uz:
    build:
      context: ./stt/vosk-api-uz
      dockerfile: Dockerfile
    ports:
    - 8031:8000
    volumes:
    - ./stt/vosk-api-uz:/app
    - ./models/vosk-api-uz:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: vosk-api-uz
      PORT: '8000'
    restart: 'no'
    container_name: model-vosk-api-uz
    stdin_open: true
    tty: true
    networks:
    - models-network
  wav2vec2_large_xlsr_uz:
    build:
      context: ./stt/wav2vec2-large-xlsr-uz
      dockerfile: Dockerfile
    ports:
    - 8032:8000
    volumes:
    - ./stt/wav2vec2-large-xlsr-uz:/app
    - ./models/wav2vec2-large-xlsr-uz:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: wav2vec2-large-xlsr-uz
      PORT: '8000'
    restart: 'no'
    container_name: model-wav2vec2-large-xlsr-uz
    stdin_open: true
    tty: true
    networks:
    - models-network
  data2vec_audio_large:
    build:
      context: ./stt/data2vec-audio-large
      dockerfile: Dockerfile
    ports:
    - 8033:8000
    volumes:
    - ./stt/data2vec-audio-large:/app
    - ./models/data2vec-audio-large:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: data2vec-audio-large
      PORT: '8000'
    restart: 'no'
    container_name: model-data2vec-audio-large
    stdin_open: true
    tty: true
    networks:
    - models-network
  zipformer_transducer:
    build:
      context: ./stt/zipformer-transducer
      dockerfile: Dockerfile
    ports:
    - 8034:8000
    volumes:
    - ./stt/zipformer-transducer:/app
    - ./models/zipformer-transducer:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: zipformer-transducer
      PORT: '8000'
    restart: 'no'
    container_name: model-zipformer-transducer
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_medium:
    build:
      context: ./stt/whisper-medium
      dockerfile: Dockerfile
    ports:
    - 8035:8000
    volumes:
    - ./stt/whisper-medium:/app
    - ./models/whisper-medium:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-medium
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-medium
    stdin_open: true
    tty: true
    networks:
    - models-network
  insanely_fast_whisper:
    build:
      context: ./stt/insanely-fast-whisper
      dockerfile: Dockerfile
    ports:
    - 8036:8000
    volumes:
    - ./stt/insanely-fast-whisper:/app
    - ./models/insanely-fast-whisper:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: insanely-fast-whisper
      PORT: '8000'
    restart: 'no'
    container_name: model-insanely-fast-whisper
    stdin_open: true
    tty: true
    networks:
    - models-network
  seamless_m4t_stt:
    build:
      context: ./stt/seamless-m4t-stt
      dockerfile: Dockerfile
    ports:
    - 8037:8000
    volumes:
    - ./stt/seamless-m4t-stt:/app
    - ./models/seamless-m4t-stt:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: seamless-m4t-stt
      PORT: '8000'
    restart: 'no'
    container_name: model-seamless-m4t-stt
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_base:
    build:
      context: ./stt/whisper-base
      dockerfile: Dockerfile
    ports:
    - 8038:8000
    volumes:
    - ./stt/whisper-base:/app
    - ./models/whisper-base:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-base
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-base
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_large_v3_turbo:
    build:
      context: ./stt/whisper-large-v3-turbo
      dockerfile: Dockerfile
    ports:
    - 8039:8000
    volumes:
    - ./stt/whisper-large-v3-turbo:/app
    - ./models/whisper-large-v3-turbo:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-large-v3-turbo
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-large-v3-turbo
    stdin_open: true
    tty: true
    networks:
    - models-network
  fasterwhisper:
    build:
      context: ./stt/FasterWhisper
      dockerfile: Dockerfile
    ports:
    - 8040:8000
    volumes:
    - ./stt/FasterWhisper:/app
    - ./models/FasterWhisper:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: FasterWhisper
      PORT: '8000'
    restart: 'no'
    container_name: model-FasterWhisper
    stdin_open: true
    tty: true
    networks:
    - models-network
  conformer_ctc:
    build:
      context: ./stt/conformer-ctc
      dockerfile: Dockerfile
    ports:
    - 8041:8000
    volumes:
    - ./stt/conformer-ctc:/app
    - ./models/conformer-ctc:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: conformer-ctc
      PORT: '8000'
    restart: 'no'
    container_name: model-conformer-ctc
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_timestamped:
    build:
      context: ./stt/whisper-timestamped
      dockerfile: Dockerfile
    ports:
    - 8042:8000
    volumes:
    - ./stt/whisper-timestamped:/app
    - ./models/whisper-timestamped:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-timestamped
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-timestamped
    stdin_open: true
    tty: true
    networks:
    - models-network
  moonshine_base:
    build:
      context: ./stt/moonshine-base
      dockerfile: Dockerfile
    ports:
    - 8043:8000
    volumes:
    - ./stt/moonshine-base:/app
    - ./models/moonshine-base:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: moonshine-base
      PORT: '8000'
    restart: 'no'
    container_name: model-moonshine-base
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_small_uz:
    build:
      context: ./stt/whisper-small-uz
      dockerfile: Dockerfile
    ports:
    - 8044:8000
    volumes:
    - ./stt/whisper-small-uz:/app
    - ./models/whisper-small-uz:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-small-uz
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-small-uz
    stdin_open: true
    tty: true
    networks:
    - models-network
  whisper_cpp:
    build:
      context: ./stt/whisper-cpp
      dockerfile: Dockerfile
    ports:
    - 8045:8000
    volumes:
    - ./stt/whisper-cpp:/app
    - ./models/whisper-cpp:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: whisper-cpp
      PORT: '8000'
    restart: 'no'
    container_name: model-whisper-cpp
    stdin_open: true
    tty: true
    networks:
    - models-network
  sensevoice_small:
    build:
      context: ./stt/sensevoice-small
      dockerfile: Dockerfile
    ports:
    - 8046:8000
    volumes:
    - ./stt/sensevoice-small:/app
    - ./models/sensevoice-small:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: sensevoice-small
      PORT: '8000'
    restart: 'no'
    container_name: model-sensevoice-small
    stdin_open: true
    tty: true
    networks:
    - models-network
  silero_stt:
    build:
      context: ./stt/silero-stt
      dockerfile: Dockerfile
    ports:
    - 8047:8000
    volumes:
    - ./stt/silero-stt:/app
    - ./models/silero-stt:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: silero-stt
      PORT: '8000'
    restart: 'no'
    container_name: model-silero-stt
    stdin_open: true
    tty: true
    networks:
    - models-network
  nemo_canary_1b:
    build:
      context: ./stt/nemo-canary-1b
      dockerfile: Dockerfile
    ports:
    - 8048:8000
    volumes:
    - ./stt/nemo-canary-1b:/app
    - ./models/nemo-canary-1b:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: nemo-canary-1b
      PORT: '8000'
    restart: 'no'
    container_name: model-nemo-canary-1b
    stdin_open: true
    tty: true
    networks:
    - models-network
  mms_1b_all:
    build:
      context: ./stt/mms-1b-all
      dockerfile: Dockerfile
    ports:
    - 8049:8000
    volumes:
    - ./stt/mms-1b-all:/app
    - ./models/mms-1b-all:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: mms-1b-all
      PORT: '8000'
    restart: 'no'
    container_name: model-mms-1b-all
    stdin_open: true
    tty: true
    networks:
    - models-network
  wavlm_large:
    build:
      context: ./stt/wavlm-large
      dockerfile: Dockerfile
    ports:
    - 8050:8000
    volumes:
    - ./stt/wavlm-large:/app
    - ./models/wavlm-large:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: wavlm-large
      PORT: '8000'
    restart: 'no'
    container_name: model-wavlm-large
    stdin_open: true
    tty: true
    networks:
    - models-network
  hubert_large_ls960:
    build:
      context: ./stt/hubert-large-ls960
      dockerfile: Dockerfile
    ports:
    - 8051:8000
    volumes:
    - ./stt/hubert-large-ls960:/app
    - ./models/hubert-large-ls960:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: hubert-large-ls960
      PORT: '8000'
    restart: 'no'
    container_name: model-hubert-large-ls960
    stdin_open: true
    tty: true
    networks:
    - models-network
  moonshine_tiny:
    build:
      context: ./stt/moonshine-tiny
      dockerfile: Dockerfile
    ports:
    - 8052:8000
    volumes:
    - ./stt/moonshine-tiny:/app
    - ./models/moonshine-tiny:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: moonshine-tiny
      PORT: '8000'
    restart: 'no'
    container_name: model-moonshine-tiny
    stdin_open: true
    tty: true
    networks:
    - models-network
  gemma_2_2b_instruct_gguf:
    build:
      context: ./llm/Gemma-2-2B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8053:8000
    volumes:
    - ./llm/Gemma-2-2B-Instruct-GGUF:/app
    - ./models/Gemma-2-2B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Gemma-2-2B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Gemma-2-2B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  qwen2_vl_2b_instruct_gguf:
    build:
      context: ./llm/Qwen2-VL-2B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8054:8000
    volumes:
    - ./llm/Qwen2-VL-2B-Instruct-GGUF:/app
    - ./models/Qwen2-VL-2B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Qwen2-VL-2B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Qwen2-VL-2B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  qwen2_5_coder_1_5b_instruct_gguf:
    build:
      context: ./llm/Qwen2.5-Coder-1.5B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8055:8000
    volumes:
    - ./llm/Qwen2.5-Coder-1.5B-Instruct-GGUF:/app
    - ./models/Qwen2.5-Coder-1.5B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Qwen2.5-Coder-1.5B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Qwen2.5-Coder-1.5B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  smollm2_1_7b_instruct_gguf:
    build:
      context: ./llm/SmolLM2-1.7B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8056:8000
    volumes:
    - ./llm/SmolLM2-1.7B-Instruct-GGUF:/app
    - ./models/SmolLM2-1.7B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: SmolLM2-1.7B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-SmolLM2-1.7B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  bge_m3:
    build:
      context: ./llm/bge-m3
      dockerfile: Dockerfile
    ports:
    - 8057:8000
    volumes:
    - ./llm/bge-m3:/app
    - ./models/bge-m3:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: bge-m3
      PORT: '8000'
    restart: 'no'
    container_name: model-bge-m3
    stdin_open: true
    tty: true
    networks:
    - models-network
  deepseek_r1_distill_llama_8b_gguf:
    build:
      context: ./llm/DeepSeek-R1-Distill-Llama-8B-GGUF
      dockerfile: Dockerfile
    ports:
    - 8058:8000
    volumes:
    - ./llm/DeepSeek-R1-Distill-Llama-8B-GGUF:/app
    - ./models/DeepSeek-R1-Distill-Llama-8B-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: DeepSeek-R1-Distill-Llama-8B-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-DeepSeek-R1-Distill-Llama-8B-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  qwen2_5_3b_instruct_gguf:
    build:
      context: ./llm/Qwen2.5-3B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8059:8000
    volumes:
    - ./llm/Qwen2.5-3B-Instruct-GGUF:/app
    - ./models/Qwen2.5-3B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Qwen2.5-3B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Qwen2.5-3B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  moondream2_gguf:
    build:
      context: ./llm/Moondream2-GGUF
      dockerfile: Dockerfile
    ports:
    - 8060:8000
    volumes:
    - ./llm/Moondream2-GGUF:/app
    - ./models/Moondream2-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Moondream2-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Moondream2-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  llama_guard_3_1b_gguf:
    build:
      context: ./llm/Llama-Guard-3-1B-GGUF
      dockerfile: Dockerfile
    ports:
    - 8061:8000
    volumes:
    - ./llm/Llama-Guard-3-1B-GGUF:/app
    - ./models/Llama-Guard-3-1B-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Llama-Guard-3-1B-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Llama-Guard-3-1B-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  deepseek_r1_distill_qwen_1_5b_gguf:
    build:
      context: ./llm/DeepSeek-R1-Distill-Qwen-1.5B-GGUF
      dockerfile: Dockerfile
    ports:
    - 8062:8000
    volumes:
    - ./llm/DeepSeek-R1-Distill-Qwen-1.5B-GGUF:/app
    - ./models/DeepSeek-R1-Distill-Qwen-1.5B-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: DeepSeek-R1-Distill-Qwen-1.5B-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-DeepSeek-R1-Distill-Qwen-1.5B-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  deepseek_coder_v2_lite_instruct_gguf:
    build:
      context: ./llm/DeepSeek-Coder-V2-Lite-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8063:8000
    volumes:
    - ./llm/DeepSeek-Coder-V2-Lite-Instruct-GGUF:/app
    - ./models/DeepSeek-Coder-V2-Lite-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: DeepSeek-Coder-V2-Lite-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-DeepSeek-Coder-V2-Lite-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  mistral_7b_instruct_v0_3_gguf:
    build:
      context: ./llm/Mistral-7B-Instruct-v0.3-GGUF
      dockerfile: Dockerfile
    ports:
    - 8064:8000
    volumes:
    - ./llm/Mistral-7B-Instruct-v0.3-GGUF:/app
    - ./models/Mistral-7B-Instruct-v0.3-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Mistral-7B-Instruct-v0.3-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Mistral-7B-Instruct-v0.3-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  hermes_3_llama_3_2_3b_gguf:
    build:
      context: ./llm/Hermes-3-Llama-3.2-3B-GGUF
      dockerfile: Dockerfile
    ports:
    - 8065:8000
    volumes:
    - ./llm/Hermes-3-Llama-3.2-3B-GGUF:/app
    - ./models/Hermes-3-Llama-3.2-3B-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Hermes-3-Llama-3.2-3B-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Hermes-3-Llama-3.2-3B-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  qwen2_5_1_5b_instruct_gguf:
    build:
      context: ./llm/Qwen2.5-1.5B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8066:8000
    volumes:
    - ./llm/Qwen2.5-1.5B-Instruct-GGUF:/app
    - ./models/Qwen2.5-1.5B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Qwen2.5-1.5B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Qwen2.5-1.5B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  nllb_200_distilled_600m:
    build:
      context: ./llm/NLLB-200-Distilled-600M
      dockerfile: Dockerfile
    ports:
    - 8067:8000
    volumes:
    - ./llm/NLLB-200-Distilled-600M:/app
    - ./models/NLLB-200-Distilled-600M:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: NLLB-200-Distilled-600M
      PORT: '8000'
    restart: 'no'
    container_name: model-NLLB-200-Distilled-600M
    stdin_open: true
    tty: true
    networks:
    - models-network
  granite_3_0_2b_instruct_gguf:
    build:
      context: ./llm/Granite-3.0-2B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8068:8000
    volumes:
    - ./llm/Granite-3.0-2B-Instruct-GGUF:/app
    - ./models/Granite-3.0-2B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Granite-3.0-2B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Granite-3.0-2B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  starcoder2_3b_gguf:
    build:
      context: ./llm/StarCoder2-3B-GGUF
      dockerfile: Dockerfile
    ports:
    - 8069:8000
    volumes:
    - ./llm/StarCoder2-3B-GGUF:/app
    - ./models/StarCoder2-3B-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: StarCoder2-3B-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-StarCoder2-3B-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  phi_3_5_mini_instruct_gguf:
    build:
      context: ./llm/Phi-3.5-mini-instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8070:8000
    volumes:
    - ./llm/Phi-3.5-mini-instruct-GGUF:/app
    - ./models/Phi-3.5-mini-instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Phi-3.5-mini-instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Phi-3.5-mini-instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  llama_3_1_8b_instruct_gguf:
    build:
      context: ./llm/Llama-3.1-8B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8071:8000
    volumes:
    - ./llm/Llama-3.1-8B-Instruct-GGUF:/app
    - ./models/Llama-3.1-8B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Llama-3.1-8B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Llama-3.1-8B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
  bge_reranker_v2_m3:
    build:
      context: ./llm/bge-reranker-v2-m3
      dockerfile: Dockerfile
    ports:
    - 8072:8000
    volumes:
    - ./llm/bge-reranker-v2-m3:/app
    - ./models/bge-reranker-v2-m3:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: bge-reranker-v2-m3
      PORT: '8000'
    restart: 'no'
    container_name: model-bge-reranker-v2-m3
    stdin_open: true
    tty: true
    networks:
    - models-network
  llama_3_2_1b_instruct_gguf:
    build:
      context: ./llm/Llama-3.2-1B-Instruct-GGUF
      dockerfile: Dockerfile
    ports:
    - 8073:8000
    volumes:
    - ./llm/Llama-3.2-1B-Instruct-GGUF:/app
    - ./models/Llama-3.2-1B-Instruct-GGUF:/app/models
    - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      MODEL_NAME: Llama-3.2-1B-Instruct-GGUF
      PORT: '8000'
    restart: 'no'
    container_name: model-Llama-3.2-1B-Instruct-GGUF
    stdin_open: true
    tty: true
    networks:
    - models-network
volumes: {}
networks:
  models-network:
    driver: bridge
